### ISSUE TITLE
项目启动相关

### ISSUE THREAD

**Issue by howell-wu** [windyrain/react-chinese-chess#4]
想请问一下，这个项目我克隆下来跑不起来，我看yarn.lock文件都是本地服务器开头的，这种我应该怎么启动呢
期待您的回复

**Comment by windyrain** [comment]
我处理一下，开发的时候没注意，连到了私有npm了，谢谢提醒

**Comment by windyrain** [comment]
似乎还有babel的问题，一起修复了，欢迎体验！

**Comment by howell-wu** [comment]
thx
